[package]
name = "rusttest"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
stm32h7xx-hal = {version = "0.16.0", features = ["stm32h747cm7","rt"]}
